export const APP_BAR_CHANGE = 'app_bar_change';

export const AUTH_CHANGE = 'AUTH_CHANGE';
export const AUTH_ERROR = 'AUTH_ERROR';

export const BALANCES_FETCHED = 'BALANCES_FETCHED';
export const BALANCE_ADDED = 'BALANCE_ADDED';
export const BALANCE_DELETED = 'BALANCE_DELETED';
export const BALANCES_FETCHING = 'BALANCES_FETCHING';

export const OVERVIEW_FETCHING = 'OVERVIEW_FETCHING';
export const OVERVIEW_FETCHED = 'OVERVIEW_FETCHED';