export const AUTH_CHANGE = 'AUTH_CHANGE';
export const AUTH_ERROR = 'AUTH_ERROR';

export const BALANCES_FETCHED = 'BALANCES_FETCHED';
export const BALANCE_ADDED = 'BALANCE_ADDED';
export const BALANCE_DELETED = 'BALANCE_DELETED';